name: Generar video con HeyGen

on:
  workflow_dispatch: {}
  push:
    paths:
      - "script.txt"

jobs:
  crear-video:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Leer guion
        id: guion
        run: |
          CONTENT=$(cat script.txt | python -c 'import sys,json; print(json.dumps(sys.stdin.read()))')
          echo "guion=$CONTENT" >> $GITHUB_OUTPUT

      - name: Llamar a HeyGen - crear video
        id: crear
        env:
          HEYGEN_API_KEY: ${{ secrets.HEYGEN_API_KEY }}
        run: |
          curl -s -X POST "https://api.heygen.com/v2/video/generate" \
            -H "x-api-key: $HEYGEN_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{
              \"title\": \"Video unidad 1\",
              \"caption\": false,
              \"video_inputs\": [
                {
                  \"avatar_id\": \"default_avatar\",
                  \"voice_id\": \"es_es_1\",
                  \"input_text\": ${{ steps.guion.outputs.guion }},
                  \"background\": {\"type\": \"color\", \"value\": \"#ffffff\"}
                }
              ],
              \"dimension\": {\"width\": 1280, \"height\": 720}
            }" > resp.json

          echo "Respuesta:"
          cat resp.json

          VIDEO_ID=$(cat resp.json | python -c 'import sys,json; print(json.load(sys.stdin).get("data",{}).get("video_id",""))')
          if [ -z "$VIDEO_ID" ]; then
            echo "No se obtuvo video_id"
            exit 1
          fi
          echo "video_id=$VIDEO_ID" >> $GITHUB_OUTPUT

      - name: Esperar a que el video esté listo
        id: esperar
        env:
          HEYGEN_API_KEY: ${{ secrets.HEYGEN_API_KEY }}
          VIDEO_ID: ${{ steps.crear.outputs.video_id }}
        run: |
          echo "Esperando a que el video $VIDEO_ID esté listo..."
          for i in {1..30}; do
            STATUS=$(curl -s -X GET "https://api.heygen.com/v1/video/status?video_id=${VIDEO_ID}" \
              -H "x-api-key: $HEYGEN_API_KEY" | python -c 'import sys,json; print(json.load(sys.stdin).get("data",{}).get("status",""))')
            echo "Intento $i - estado: $STATUS"
            if [ "$STATUS" = "completed" ]; then
              URL=$(curl -s -X GET "https://api.heygen.com/v1/video/status?video_id=${VIDEO_ID}" \
                -H "x-api-key: $HEYGEN_API_KEY" | python -c 'import sys,json; print(json.load(sys.stdin)["data"]["video_url"])')
              echo "video_url=$URL" >> $GITHUB_OUTPUT
              exit 0
            fi
            sleep 10
          done
          echo "No se completó el video a tiempo"
          exit 1

      - name: Mostrar URL del video
        run: |
          echo "✅ Tu video está listo:"
          echo "${{ steps.esperar.outputs.video_url }}"
