name: Generar video con HeyGen (Corregido)

on:
  workflow_dispatch: {}
  push:
    paths:
      - "script-*.txt"

jobs:
  generar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generar videos con HeyGen
        env:
          HEYGEN_API_KEY: ${{ secrets.HEYGEN_API_KEY }}
        run: |
          for file in script-*.txt; do
            echo "Procesando $file..."
            CONTENT=$(jq -Rs . < "$file")
            NAME=$(basename "$file" .txt)
            echo "Generando video para $NAME"
            curl -X POST "https://api.heygen.com/v2/video/generate" \
              -H "x-api-key: $HEYGEN_API_KEY" \
              -H "Content-Type: application/json" \
              -d "{
                \"title\": \"Video $NAME\",
                \"aspect_ratio\": \"16:9\",
                \"video_inputs\": [
                  {
                    \"type\": \"avatar\",
                    \"input_text\": $CONTENT,
                    \"input_text_language\": \"es\",
                    \"avatar_id\": \"default\",
                    \"voice_id\": \"default\"
                  }
                ]
              }"
            echo ""
          done
